trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'your-azure-subscription'
  resourceGroupName: 'your-resource-group'
  location: 'eastus'
  storageAccountName: 'yourstorageaccount'
  containerName: 'yourcontainer'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '6.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        dotnet build --configuration $(buildConfiguration)
      displayName: 'Build project'

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: 'Azure'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: $(azureSubscription)
              subscriptionId: $(azureSubscription)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(resourceGroupName)
              location: $(location)
              templateLocation: 'Linked artifact'
              csmFile: '$(Pipeline.Workspace)/drop/template.json'
              csmParametersFile: '$(Pipeline.Workspace)/drop/parameters.json'
              deploymentMode: 'Incremental'

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage account create --name $(storageAccountName) --resource-group $(resourceGroupName) --location $(location) --sku Standard_LRS
                az storage container create --name $(containerName) --account-name $(storageAccountName)
